#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.269
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



public partial class MeuBanco : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBebida(Bebida instance);
  partial void UpdateBebida(Bebida instance);
  partial void DeleteBebida(Bebida instance);
  partial void InsertComida(Comida instance);
  partial void UpdateComida(Comida instance);
  partial void DeleteComida(Comida instance);
  partial void InsertExercicio(Exercicio instance);
  partial void UpdateExercicio(Exercicio instance);
  partial void DeleteExercicio(Exercicio instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  #endregion
	
	public MeuBanco(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MeuBanco(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}

	public System.Data.Linq.Table<Bebida> Bebida
	{
		get
		{
			return this.GetTable<Bebida>();
		}
	}
	
	public System.Data.Linq.Table<Comida> Comida
	{
		get
		{
			return this.GetTable<Comida>();
		}
	}
	
	public System.Data.Linq.Table<Exercicio> Exercicio
	{
		get
		{
			return this.GetTable<Exercicio>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class Bebida : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nome;
	
	private System.Nullable<double> _PorcaoPadrao;
	
	private System.Nullable<double> _CaloriaPorcao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnPorcaoPadraoChanging(System.Nullable<double> value);
    partial void OnPorcaoPadraoChanged();
    partial void OnCaloriaPorcaoChanging(System.Nullable<double> value);
    partial void OnCaloriaPorcaoChanged();
    #endregion
	
	public Bebida()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(100)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcaoPadrao", DbType="Float")]
	public System.Nullable<double> PorcaoPadrao
	{
		get
		{
			return this._PorcaoPadrao;
		}
		set
		{
			if ((this._PorcaoPadrao != value))
			{
				this.OnPorcaoPadraoChanging(value);
				this.SendPropertyChanging();
				this._PorcaoPadrao = value;
				this.SendPropertyChanged("PorcaoPadrao");
				this.OnPorcaoPadraoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriaPorcao", DbType="Float")]
	public System.Nullable<double> CaloriaPorcao
	{
		get
		{
			return this._CaloriaPorcao;
		}
		set
		{
			if ((this._CaloriaPorcao != value))
			{
				this.OnCaloriaPorcaoChanging(value);
				this.SendPropertyChanging();
				this._CaloriaPorcao = value;
				this.SendPropertyChanged("CaloriaPorcao");
				this.OnCaloriaPorcaoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class Comida : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nome;
	
	private System.Nullable<double> _PorcaoPadrao;
	
	private System.Nullable<double> _CaloriasPorcao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnPorcaoPadraoChanging(System.Nullable<double> value);
    partial void OnPorcaoPadraoChanged();
    partial void OnCaloriasPorcaoChanging(System.Nullable<double> value);
    partial void OnCaloriasPorcaoChanged();
    #endregion
	
	public Comida()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(100)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcaoPadrao", DbType="Float")]
	public System.Nullable<double> PorcaoPadrao
	{
		get
		{
			return this._PorcaoPadrao;
		}
		set
		{
			if ((this._PorcaoPadrao != value))
			{
				this.OnPorcaoPadraoChanging(value);
				this.SendPropertyChanging();
				this._PorcaoPadrao = value;
				this.SendPropertyChanged("PorcaoPadrao");
				this.OnPorcaoPadraoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriasPorcao", DbType="Float")]
	public System.Nullable<double> CaloriasPorcao
	{
		get
		{
			return this._CaloriasPorcao;
		}
		set
		{
			if ((this._CaloriasPorcao != value))
			{
				this.OnCaloriasPorcaoChanging(value);
				this.SendPropertyChanging();
				this._CaloriasPorcao = value;
				this.SendPropertyChanged("CaloriasPorcao");
				this.OnCaloriasPorcaoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class Exercicio : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nome;
	
	private System.Nullable<double> _TempoPadrao;
	
	private System.Nullable<double> _CaloriasTempo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTempoPadraoChanging(System.Nullable<double> value);
    partial void OnTempoPadraoChanged();
    partial void OnCaloriasTempoChanging(System.Nullable<double> value);
    partial void OnCaloriasTempoChanged();
    #endregion
	
	public Exercicio()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(100)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoPadrao", DbType="Float")]
	public System.Nullable<double> TempoPadrao
	{
		get
		{
			return this._TempoPadrao;
		}
		set
		{
			if ((this._TempoPadrao != value))
			{
				this.OnTempoPadraoChanging(value);
				this.SendPropertyChanging();
				this._TempoPadrao = value;
				this.SendPropertyChanged("TempoPadrao");
				this.OnTempoPadraoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriasTempo", DbType="Float")]
	public System.Nullable<double> CaloriasTempo
	{
		get
		{
			return this._CaloriasTempo;
		}
		set
		{
			if ((this._CaloriasTempo != value))
			{
				this.OnCaloriasTempoChanging(value);
				this.SendPropertyChanging();
				this._CaloriasTempo = value;
				this.SendPropertyChanged("CaloriasTempo");
				this.OnCaloriasTempoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nome;
	
	private string _Sexo;
	
	private System.Nullable<int> _Altura;
	
	private System.Nullable<int> _Peso;
	
	private System.Nullable<int> _Idade;
	
	private System.Nullable<double> _IMC;
	
	private System.Nullable<int> _CaloriaIdeal;
	
	private System.Nullable<int> _CaloriaAtual;
	
	private System.Nullable<System.DateTime> _UltimaData;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnAlturaChanging(System.Nullable<int> value);
    partial void OnAlturaChanged();
    partial void OnPesoChanging(System.Nullable<int> value);
    partial void OnPesoChanged();
    partial void OnIdadeChanging(System.Nullable<int> value);
    partial void OnIdadeChanged();
    partial void OnIMCChanging(System.Nullable<double> value);
    partial void OnIMCChanged();
    partial void OnCaloriaIdealChanging(System.Nullable<int> value);
    partial void OnCaloriaIdealChanged();
    partial void OnCaloriaAtualChanging(System.Nullable<int> value);
    partial void OnCaloriaAtualChanged();
    partial void OnUltimaDataChanging(System.Nullable<System.DateTime> value);
    partial void OnUltimaDataChanged();
    #endregion
	
	public Usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(100)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="NVarChar(100)")]
	public string Sexo
	{
		get
		{
			return this._Sexo;
		}
		set
		{
			if ((this._Sexo != value))
			{
				this.OnSexoChanging(value);
				this.SendPropertyChanging();
				this._Sexo = value;
				this.SendPropertyChanged("Sexo");
				this.OnSexoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Altura", DbType="Int")]
	public System.Nullable<int> Altura
	{
		get
		{
			return this._Altura;
		}
		set
		{
			if ((this._Altura != value))
			{
				this.OnAlturaChanging(value);
				this.SendPropertyChanging();
				this._Altura = value;
				this.SendPropertyChanged("Altura");
				this.OnAlturaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="Int")]
	public System.Nullable<int> Peso
	{
		get
		{
			return this._Peso;
		}
		set
		{
			if ((this._Peso != value))
			{
				this.OnPesoChanging(value);
				this.SendPropertyChanging();
				this._Peso = value;
				this.SendPropertyChanged("Peso");
				this.OnPesoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idade", DbType="Int")]
	public System.Nullable<int> Idade
	{
		get
		{
			return this._Idade;
		}
		set
		{
			if ((this._Idade != value))
			{
				this.OnIdadeChanging(value);
				this.SendPropertyChanging();
				this._Idade = value;
				this.SendPropertyChanged("Idade");
				this.OnIdadeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMC", DbType="Float")]
	public System.Nullable<double> IMC
	{
		get
		{
			return this._IMC;
		}
		set
		{
			if ((this._IMC != value))
			{
				this.OnIMCChanging(value);
				this.SendPropertyChanging();
				this._IMC = value;
				this.SendPropertyChanged("IMC");
				this.OnIMCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriaIdeal", DbType="Int")]
	public System.Nullable<int> CaloriaIdeal
	{
		get
		{
			return this._CaloriaIdeal;
		}
		set
		{
			if ((this._CaloriaIdeal != value))
			{
				this.OnCaloriaIdealChanging(value);
				this.SendPropertyChanging();
				this._CaloriaIdeal = value;
				this.SendPropertyChanged("CaloriaIdeal");
				this.OnCaloriaIdealChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriaAtual", DbType="Int")]
	public System.Nullable<int> CaloriaAtual
	{
		get
		{
			return this._CaloriaAtual;
		}
		set
		{
			if ((this._CaloriaAtual != value))
			{
				this.OnCaloriaAtualChanging(value);
				this.SendPropertyChanging();
				this._CaloriaAtual = value;
				this.SendPropertyChanged("CaloriaAtual");
				this.OnCaloriaAtualChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaData", DbType="DateTime")]
	public System.Nullable<System.DateTime> UltimaData
	{
		get
		{
			return this._UltimaData;
		}
		set
		{
			if ((this._UltimaData != value))
			{
				this.OnUltimaDataChanging(value);
				this.SendPropertyChanging();
				this._UltimaData = value;
				this.SendPropertyChanged("UltimaData");
				this.OnUltimaDataChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
